auth:
  registry.cn-shenzhen.aliyuncs.com:
    username: xxxx
    password: xxxx
images:
  registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343: registry.cn-shenzhen.aliyuncs.com/zodance/kube-webhook-certgen:v20220916-gd32f8c343
  registry.k8s.io/ingress-nginx/controller:v1.4.0: registry.cn-shenzhen.aliyuncs.com/zodance/controller:v1.4.0
